Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stackName}-users
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH       
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S      
      Tags:
        - Key: Environment
          Value: ${self:custom.stage}
        - Key: Name
          Value: users-table
  RemindersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stackName}-reminders
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE          
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S      
        - AttributeName: id
          AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_IMAGE          
      Tags:
        - Key: Environment
          Value: ${self:custom.stage}
        - Key: Name
          Value: reminders-table