name: "Build & Deploy Backend"

on:
  push:
    branches:
      - stage
jobs:
  main:
    name: Build & Deploy
    runs-on: ubuntu-latest
      SLS_DEBUG: "*"
    steps:
      - name: Setup Dynamic Variables
        run: |
          echo "AWS_ACCESS_KEY_ID=${{secrets['STAGE_AWS_ACCESS_KEY_ID']}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{secrets['STAGE_AWS_SECRET_ACCESS_KEY']}}" >> $GITHUB_ENV
      - name: Source Code Checkout
        uses: actions/checkout@v2
      - name: Install SLS plugins
        run: yarn install
      - name: Deploy Backend
        run: ./node_modules/.bin/sls deploy -v
